### ISSUE TITLE
RocksDB huge memory usage

### ISSUE THREAD

**Issue by bidoudan** [trezor/blockbook#721] opened 2021-12-31 11:44 UTC
Hello there,
Requesting ` /api/v2/address/<address>?details=txs` for several times, RocksDB uses a lot of memory, 
We've tried to run blockbook with `-dbcache=0 -workers=1 -notxcache` but nothing changed
Is there any solution for this issue.
Thanks in advance.

**Comment by martinboehm** [comment] 2022-01-09 18:45
Hi, you are not very specific neither by what is "huge" memory usage nor what coin you are using. However, RocksDB is memory hungry and you should use server that is reasonably dimensioned. From the settings you mentioned, only `-dbcache=0` has effect on memory consumption of synchronized Blockbook (`-workers=1` has effect only during initial synchronization).

**Comment by bidoudan** [comment] 2022-01-09 22:05
Thanks for your response, we are using ravencoin, when we send request that I mentioned before for several times in some addresses used in great number of transactions, RocksDB takes more than usual to respond and it uses a lot of memory we are wondering if it was a syncing problem ?
Is it normal for such kind of addresses or we should change something.
Thanks

**Comment by prusnak** [comment] 2022-02-23 18:34
Essentially a duplicate of https://github.com/trezor/blockbook/issues/43

Yes, RocksDB needs 32 GB of memory.

**Closed by prusnak** 2022-02-23 18:34 UTC
