### ISSUE TITLE
Xpub API doesn't work for litecoin zpub

### ISSUE THREAD

**Issue by hewigovens** [trezor/blockbook#138] opened 2019-03-26 05:17 UTC
Hi,

We just upgrade our Dash/Zcash/Litecoin blockbook nodes to 0.2.1, Dash and Zcash work fine, but Litecoin doesn't (both balance and utxo)

`zpub6qUNvXS4CxMx99VEGq1UQHi3ofmoKerRwVdHYbq1QTxPxCrMkbq6G4id3yH1gpkp37NzAFXKdTLbJbSKjudEcrwqaMgFakiyNVTovuw4RYH` returns zero balance

could you please help to check? @martinboehm 

Thanks

**Comment by martinboehm** [comment] 2019-03-26 07:35
It works fine, however you have to use magic (the xpub prefix) as defined in trezor-common, i.e for [litecoin](https://github.com/trezor/trezor-common/blob/master/defs/bitcoin/litecoin.json) `"xpub_magic": 27108450`, `"xpub_magic_segwit_p2sh": 28471030`. Then you get litecoin xpubs like this:

```
Ltub2Y8PyEMWQVgiX4L4gVzU8PakBTQ2WBxFdS6tJARQeasUUfXmBut2jGShnQyD3jgyBf7mmvs5jPNgmgXad5J6M8a8FiZK78dbT21fYtTAC9a
Mtub2syZtptY6mWCxNgC59ji2ELzxifydR33xbfT5w1AcQKfEd1BrsnzraY9asxRJcQbUYuFPHGfa8opGaXQQiGEPXKDcDEjUPFXTzS1gQMYtnX
```

I will update the documentation so that it clarifies this issue.

**Comment by hewigovens** [comment] 2019-03-26 07:44
So blockbook doesn't support zpub for Litecoin? Litecoin doesn't define zpub equivalent, 
unlike ltub (27108450) and mtub (28471030), it just uses zpub (78792518) from bitcoin for native segwit

**Comment by martinboehm** [comment] 2019-03-26 08:06
Actually, Blockbook does support native segwit xpubs. The problem is that trezor-common does not define native segwit magic for litecoin and Blockbook is taking the definitions from there. 

If you add the entry "xpub_magic_segwit_native": 78792518 to your [litecoin.json](https://github.com/trezor/blockbook/blob/master/configs/coins/litecoin.json) config, it will work.

@prusnak does it make sense for us to add litecoin segwit native xpub magic to trezor-common? I could make a pull request...

**Comment by hewigovens** [comment] 2019-03-26 08:11
Do we need to rebuild the deb?

**Comment by martinboehm** [comment] 2019-03-26 08:15
I don't think so, just update the config file and restart the service.

**Comment by hewigovens** [comment] 2019-03-26 08:32
Thanks it works!

**Comment by prusnak** [comment] 2019-03-26 10:33
@hewigovens please check with the Electrum-LTC team what value they use for "Litecoin zpub". We'll add this value to the config.

**Comment by hewigovens** [comment] 2019-03-26 10:42
We did refer to Electrum LTC when we implement native segwit for Litecoin

**Comment by hewigovens** [comment] 2019-03-26 10:59
![Screen Shot 2019-03-26 at 18 58 27](https://user-images.githubusercontent.com/360470/54992045-3d92e980-4ff9-11e9-868c-d4fcc4e486a9.png)

**Comment by prusnak** [comment] 2019-03-26 11:24
Fixed in https://github.com/trezor/trezor-common/commit/792a4eddb5afa366181b7b2f8a5d84532b31a6a1

Closing

**Closed by prusnak** 2019-03-26 11:24 UTC

**Comment by martinboehm** [comment] 2019-03-26 12:18
The commit b8eca9c25e1b9ae821ef25b7eb7740e4020e6621 updated litecoin.json and other coin configs from trezor-common.

**Comment by hewigovens** [comment] 2019-03-26 12:25
@prusnak @martinboehm 👍
