### ISSUE TITLE
Decred: xpub_magic fails to parse

### ISSUE THREAD

**Issue by dajohi** [trezor/blockbook#243] opened 2019-07-23 13:11 UTC
Decred needs to use https://github.com/decred/dcrd/tree/master/hdkeychain

**Comment by martinboehm** [comment] 2019-07-23 14:29
I do not know exactly what the problem is, however if you need some special functionality for address derivation, you will have to override `BitcoinParser.DeriveAddressDescriptors` and `BitcoinParser.DeriveAddressDescriptorsFromTo` in the decred parser and implement it.

**Comment by dajohi** [comment] 2019-07-23 15:16
yep, working on a patch :)

**Comment by dajohi** [comment] 2019-07-24 20:38
https://github.com/decred/dcrd/pull/1800

**Comment by dajohi** [comment] 2019-07-24 20:45
Not sure how to pull that in unless blockbook repo converts to go modules and drops dep.

**Comment by martinboehm** [comment] 2019-07-24 21:10
What exactly is the reason that you cannot use our hdkeychain? If it is minor, you could make a pull request to this repo https://github.com/martinboehm/btcutil.

**Comment by martinboehm** [comment] 2019-07-26 13:11
If you rebase your PR to the latest master, it should reference the btcutil library with your changes.

**Comment by martinboehm** [comment] 2019-07-29 21:34
I think I can close this as the Decred pull request is proceeding.

**Closed by martinboehm** 2019-07-29 21:34 UTC
