### ISSUE TITLE
BTC address showing negative value in explorer

### ISSUE THREAD

**Issue by karel-3d** [trezor/blockbook#19] opened 2018-07-04 15:31 UTC
This address has negative value in explorer

https:/[url]/explorer/address/3JoptT3Po7AnvuAZ7spXGtPxZxdDsEzzj3

**Comment by martinboehm** [comment] 2018-07-23 08:42
The problem is fixed by the commit f2274ce43ce3403bf14994ce367048f59c4310c2.

**Closed by martinboehm** 2018-07-23 08:42 UTC
