### ISSUE TITLE
Address Encoding Inconsistency

### ISSUE THREAD

**Issue by wlc-** [trezor/blockbook#69] opened 2018-10-02 23:05 UTC
I encountered a strange issue. I have just installed blockbook for myriad and it seems some addresses are displayed as bitcoin addresses and some as myriad addresses. 

You can clearly see the issue here:
https://blockbook.myralicious.com/block/c74c617d39d67e8cf7eb095f94670df054d36944468ef215d766168866a1abca

I cannot figure out why this occurs.
Do you have any idea?

**Comment by wakiyamap** [comment] 2018-10-03 08:38
Perhaps you are calling with default BTC params here(`txscript.ExtractPkScriptAddrs(script, p.Params)`).
https://github.com/trezor/blockbook/blob/master/bchain/coins/btc/bitcoinparser.go#L128

It seems that `btcutil` is making changes, so I will try it after the change is complete.

**Comment by martinboehm** [comment] 2018-10-03 08:43
Yes, we are trying to further isolate the coins. The default implementation of `btcutil` always registered bitcoin and bitcoin testnet, we are going to remove it.

**Comment by wlc-** [comment] 2018-10-03 09:52
Ok, but would that explain why it only happens on some addresses?

**Comment by martinboehm** [comment] 2018-10-03 16:35
I found out the reason and it is not the coin isolation. The problem is that the incorrectly shown addresses (for example 16gSq5NgEwfhTGfmXns4Amd6RsJXNpfimZ) are `pay to public key`, the correctly shown addresses are `pay to public key hash`. There is a bug in the `btcutil` library which causes the problem. We are going to fix the `btcutil` library.

There is an additional issue (caused by the design decision in Blockbook) with `pay to public key` addresses: bitcoin type coins in Blockbook use public key scripts, not addresses (as the value returned by by the abstraction `bchain.AddressDescriptor` from parsers) to index data. When searching for an address in explorer, Blockbook must convert the address to the script before the lookup. 
The problem with `pay to public key` address is that it is the same as `pay to public key hash`, but has different script (which cannot be obtained from the address). Blockbook therefore does not find the transactions of  `pay to public key` address and also computes balances of `pay to public key` and `pay to public key hash` separately, with different results than returned some other explorers.

Fortunately there is a way how to change this behavior: in the `parser.GetAddrDescFromVout` and `parser.GetScriptFromAddrDesc` you could detect `pay to public key` script and convert them to `pay to public key hash` script. We are not currently doing this in our coin implementations but I want to let you know about the issue and possible solution.

**Comment by wlc-** [comment] 2018-10-03 17:53
Ahh I see, but does not this issue (with pay to public key addresses) affect bitcoin and other coins also?

**Comment by wlc-** [comment] 2018-10-04 09:12
Nicely done! It encodes the addresses correctly now.

Of course i cant lookup P2PK addresses, is the solution you suggested anything you are planning to implement in the future?

**Comment by martinboehm** [comment] 2018-10-09 10:07
Yes, we are going to implement it. I am closing this issue and opening a new one for the P2PK addresses.

**Closed by martinboehm** 2018-10-09 10:07 UTC
